databases:
  - name: NextPlay_DB
    databaseName: nextplay_db
    user: NextPlay
    region: singapore

services:
  - type: web
    name: NextPlay
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: NextPlay_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
